[tool.poetry]
name = "othello"
version = "0.1.0"
description = "Othello game engine"
authors = ["Jason R. Carrete <jasoncarrete5@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pylint = "^2.4"
pytest = "^5.2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
